repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
  - repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        entry: autoflake --in-place --remove-all-unused-imports --remove-duplicate-keys --remove-unused-variables -v
        language: python
        types: [python]
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.1.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.351
    hooks:
      - id: pyright
  # Hooks that run in local environment (not isolated venv) as they need
  # same dependencies as our package.
  - repo: local
    hooks:
      # Run mypy directly from local repo rather than using mirror-mypy
      # so that it uses installed dependencies. Adapted from:
      # https://jaredkhan.com/blog/mypy-pre-commit
      - id: mypy
        name: mypy
        language: system
        types: [python]
        entry: mypy --follow-imports=silent --show-error-codes --check-untyped-defs
        # use require_serial so that script
        # is only called once per commit
        require_serial: true
        # Print the number of files as a sanity-check
        verbose: true
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0  # pick a git hash / tag to point to
    hooks:
    -   id: pydocstyle
