[project]
name = "robust-llm"
description = "Testing the robustness of LLMs"
requires-python = ">=3.10"
version="0.0.1"

dependencies = [
    "evaluate",
    "datasets",
    "huggingface_hub",
    "hydra-core",
    "torch",
    "transformers[accelerate]",
    "simple_parsing",
    "scikit-learn",
    # Bigger than this will break TextAttack
    "scipy<1.13.0",
    "textattack",
    # TF embeddings are used in some TextAttack attacks, even though models are in pytorch
    "tensorflow>=2.9.1",
    "tensorflow_hub",
    "trl",
    "wandb",
]
[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "pre-commit",
    "mypy",
    "pyright",
    # Needed for mypy to type check PyYAML
    "types-PyYAML",
    "pytest",
    "hypothesis",
    "pytest-cov",
    "flake8",
    "names-generator",
]

[tool.setuptools.packages.find]
namespaces = false

[tool.isort]
profile = "black"
# Necessary because of directories with
# packages with the same name
known_third_party = ["datasets", "trl", "wandb"]

[tool.pyright]
venvPath = "."
venv = "venv"
include = ["robust_llm"]
pythonVersion = "3.10"

[tool.mypy]
ignore_missing_imports = true
mypy_path = ["robust_llm", "tests"]
python_version = "3.10"
