[project]
name = "robust-llm"
description = "Testing the robustness of LLMs"
requires-python = ">=3.10"
version="0.0.1"

dependencies = [
    "evaluate",
    "datasets",
    "huggingface_hub",
    "hydra-core",
    "torch",
    "transformers[accelerate]",
    "simple_parsing",
    "scikit-learn",
    "textattack",
    # TF embeddings are used in some TextAttack attacks, even though models are in pytorch
    "tensorflow==2.9.1",
    "tensorflow_hub",
    "wandb",
]
[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "mypy",
    "pre-commit",
    "pyright",
    "pytest",
    "pytest-cov",
    "flake8",
    "names-generator",
]

[tool.setuptools.packages.find]
namespaces = false

[tool.isort]
profile = "black"
known_third_party = ["wandb"]  # necessary because of "wandb" directory

[tool.pyright]
venvPath = "."
venv = "venv"
include = ["robust_llm"]
pythonVersion = "3.10"
