[project]
name = "robust-llm"
description = "Testing the robustness of LLMs"
requires-python = ">=3.10"
version="0.0.1"

dependencies = [
    "evaluate",
    "datasets",
    "huggingface_hub",
    "hydra-core",
    "torch",
    "transformers[accelerate]",
    "simple_parsing",
    "scikit-learn",
    "textattack",
    "wandb",
]
[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "mypy",
    "pre-commit",
    "pyright",
    "pytest",
]

[tool.setuptools.packages.find]
namespaces = false

[tool.pyright]
venvPath = "."
venv = "venv"
include = ["robust_llm"]
