[project]
name = "robust-llm"
description = "Testing the robustness of LLMs"
requires-python = ">=3.10"
version="0.0.1"

dependencies = [
    "evaluate",
    "torch",
    "transformers[accelerate]",
    "huggingface_hub",
    "datasets",
    "simple_parsing",
    "scikit-learn",
    "wandb",
]
[project.optional-dependencies]
dev = [
    "black",
    "mypy",
    "pre-commit",
    "pytest",
]


[tool.setuptools.packages.find]
namespaces = false
