version: 2.1

orbs:
  python: circleci/python@1.5.0
  codecov: codecov/codecov@3.3.0


commands:
  install-dependencies:
    description: "Check out and update Python dependencies."
    steps:
      - checkout
      - run:
          name: Install robust-llm
          command: |
            pip install -e '.[dev]'

  store-test-output:
    description: "Store the output of tests."
    steps:
      - store_artifacts:
          path: /tmp/test-reports
          destination: test-reports

      - store_test_results:
          path: /tmp/test-reports

      - store_artifacts:
          path: /tmp/resource-usage
          destination: resource-usage

jobs:
  pytest:
    docker:
      - image: cimg/python:3.10.13
    steps:
      - install-dependencies
      - run:
          name: Run tests
          command: |
            pytest --cov=robust_llm \
              --cov=tests --junitxml=/tmp/test-reports/junit.xml \
              --durations=500 -vv tests/
            mv .coverage .coverage.robust_llm
            coverage combine  # rewrite paths from virtualenv to src/
          environment:
            WANDB_MODE: offline
      - codecov/upload
      - store-test-output

  lint:
    docker:
      - image: cimg/python:3.10.13
    steps:
      - install-dependencies
      - run:
          name: black
          command: |
            black --version
            black . --check
      - run:
          name: isort
          command: |
            isort --version
            isort robust_llm --check --verbose
      - run:
          name: pyright
          command: |
            pyright --version
            pyright .
      - run:
          name: flake8
          command: |
            flake8 --version
            flake8 . -v --exclude venv
        # TODO maybe add codespell


workflows:
  tests:
    jobs:
      - pytest
      - lint
