version: 2.1

orbs:
  python: circleci/python@1.5.0

commands:
  install-dependencies:
    description: "Check out and update Python dependencies."
    steps:
      - checkout
      - run:
          name: Install robust-llm
          command: |
            pip install -e '.[dev]'

jobs:
  pytest:
    docker:
      - image: cimg/python:3.10.13
    steps:
      - install-dependencies
      - run:
          name: Run tests
          command: pytest
          environment:
            WANDB_MODE: offline

  lint:
    docker:
      - image: cimg/python:3.10.13
    steps:
      - install-dependencies
      - run:
          name: black
          command: |
            black --version
            black . --check
      - run:
          name: isort
          command: |
            isort --version
            isort robust_llm --check --verbose
      - run:
          name: pyright
          command: |
            pyright --version
            pyright .
        # TODO maybe add flake8 & codespell

workflows:
  tests:
    jobs:
      - pytest
      - lint
