# Based on https://github.com/AlignmentResearch/learned-planners/blob/main/k8s/runner.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: {NAME}
  labels:
    kueue.x-k8s.io/queue-name: farai
    wandb-project: {WANDB_PROJECT}
    wandb-entity: {WANDB_ENTITY}
    launch-id: {LAUNCH_ID}
spec:
  suspend: true
  template:
    metadata:
      generateName: {NAME}
    spec:
      priorityClassName: {PRIORITY}
      volumes:
        - name: robust-llm-storage
          persistentVolumeClaim:
            claimName: robust-llm
        - name: devshm
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi
      containers:
        - name: devbox-container
          image: "ghcr.io/alignmentresearch/robust-llm:{CONTAINER_TAG}"
          command:
            - bash
            - -c
            - |
              git clone https://github.com/AlignmentResearch/robust-llm.git && cd robust-llm && git checkout {COMMIT_HASH} && git submodule update --recursive && {COMMAND}
          resources:
            requests:
              cpu: {CPU}
            limits:
              memory: {MEMORY}
              nvidia.com/gpu: {GPU}
          volumeMounts:
            - name: robust-llm-storage
              mountPath: /robust_llm_data
            # This is needed as for multi-GPU training, accelerate needs to write
            # to /dev/shm and the default size is too small
            - name: devshm
              mountPath: /dev/shm
          env:
            - name: GIT_ASKPASS
              value: "true"
            - name: GITHUB_PAT
              valueFrom:
                secretKeyRef:
                  name: github-credentials
                  key: pat
            - name: GIT_CONFIG_PARAMETERS
              value: "'credential.https://github.com.username=$(GITHUB_PAT)'"
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb
                  key: api-key
            - name: WANDB_ENTITY
              value: {WANDB_ENTITY}
            - name: WANDB_PROJECT
              value: {WANDB_PROJECT}
            - name: WANDB_MODE
              value: {WANDB_MODE}
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface
                  key: token
      restartPolicy: Never
      imagePullSecrets:
        - name: docker
  backoffLimit: 0 # if the job fails, don't retry
