---
apiVersion: batch/v1
kind: Job
metadata:
  name: devbox
  labels:
    kueue.x-k8s.io/queue-name: farai
spec:
  suspend: true
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: devbox
    spec:
      priorityClassName: interactive
      volumes:
        - name: working-storage
          persistentVolumeClaim:
            claimName: devbox-storage
        - name: robust-llm-storage
          persistentVolumeClaim:
            claimName: robust-llm
        - name: devshm
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi
      containers:
        - name: devbox-container
          image: ghcr.io/alignmentresearch/robust-llm:latest
          args: ["sleep", "2d"]
          resources:
            requests:
              cpu: 14
            limits:
              memory: "60G"
              nvidia.com/gpu: 1
          volumeMounts:
            - name: working-storage
              mountPath: /home/dev
            - name: robust-llm-storage
              mountPath: /robust_llm_data
            # This is needed as for multi-GPU training, accelerate needs to write
            # to /dev/shm and the default size is too small
            - name: devshm
              mountPath: /dev/shm
          env:
            - name: GIT_ASKPASS
              value: "true"
            - name: GITHUB_PAT
              valueFrom:
                secretKeyRef:
                  name: github-credentials
                  key: pat
            - name: GIT_CONFIG_PARAMETERS
              value: "'credential.https://github.com.username=$(GITHUB_PAT)'"
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb
                  key: api-key
            - name: WANDB_ENTITY
              value: "farai"
            - name: WANDB_PROJECT
              value: "robust-llm"
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface
                  key: token
      imagePullSecrets:
        - name: docker
      restartPolicy: Never
