---
apiVersion: batch/v1
kind: Job
metadata:
  name: build-image
  labels:
    kueue.x-k8s.io/queue-name: farai
spec:
  suspend: true
  backoffLimit: 0
  template:
    metadata:
      name: kaniko
    spec:
      priorityClassName: normal-batch
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - --dockerfile=Dockerfile
            - "--context=git://github.com/AlignmentResearch/robust-llm.git#refs/heads/$(BRANCH_NAME)"
            - --git=recurse-submodules=true
            - --cache=true
            - --cache-repo=ghcr.io/alignmentresearch/robust-llm/cache
            - "--destination=ghcr.io/alignmentresearch/robust-llm:$(BRANCH_NAME)"
            - --destination=ghcr.io/alignmentresearch/robust-llm:latest
            - --verbosity=debug
          volumeMounts:
            - name: docker
              mountPath: /kaniko/.docker
          env:
            - name: GIT_ASKPASS
              value: "false"
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: github-credentials
                  key: pat
            - name: BRANCH_NAME
              value: "main"
          resources:
            requests:
              cpu: 1
            limits:
              memory: "45G"
      restartPolicy: Never
      imagePullSecrets:
        - name: docker
      volumes:
        - name: docker
          secret:
            secretName: docker
            items:
              - key: .dockerconfigjson
                path: config.json
        - name: github-credentials
          secret:
            secretName: github-credentials
