defaults:
- TRL
- /model@adversary: pythia-14m
- _self_

adversary:
  inference_type: "trl"

batch_size: 10
mini_batch_size: 10
gradient_accumulation_steps: 1
learning_rate: 3e-6
ppo_epochs: 3
model_save_path_prefix: null
