name: Auto-approve experiments PRs

on:
  pull_request:
    branches:
      - main
      - oskar/auto-approve-experiments

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check changed files
        id: check_files
        run: |
          git fetch
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "Changed files: $CHANGED_FILES"
          ALLOWED=true
          for FILE in $CHANGED_FILES; do
            if [[ ! "$FILE" =~ ^(experiments/|scripts/|robust_llm/hydra_conf/experiment/|robust_llm/plotting_utils/experiments/) ]]; then
              ALLOWED=false
              break
            fi
          done
          echo "ALLOWED=$ALLOWED" >> $GITHUB_ENV

      - name: Approve PR
        if: ${{ env.ALLOWED == 'true' }}
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
